packages:
  - packages/*

catalogs:
  build:
    conventional-changelog-metahub: ^4.0.0
    standard-version: ^9.0.0
    tsc-alias: ^1.0.0
    tsc-esm-fix: ^3.0.0
    tsconfig-paths: ^4.0.0
    tsx: ^4.0.0
    typescript: ^5.0.0

  image:
    sharp: '>=0.34.0'

  lint:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.0.0
    '@eslint/compat': ^1.0.0
    '@eslint/js': ^9.0.0
    eslint: ^9.18.0
    eslint-config-prettier: ^10.0.0
    eslint-import-resolver-typescript: ^4.0.0
    eslint-plugin-better-tailwindcss: ^3.1.0
    eslint-plugin-compat: ^6.0.0
    eslint-plugin-import: ^2.32.0
    eslint-plugin-jsdoc: ^61.0.0
    eslint-plugin-no-secrets: ^2.0.0
    eslint-plugin-react: ^7.0.0
    eslint-plugin-sonarjs: ^3.0.0
    eslint-plugin-storybook: ^9.0.0
    typescript-eslint: ^8.0.0
    husky: ^9.0.0
    leasot: ^14.0.0
    lint-staged: ^16.0.0
    prettier: ^3.0.0
    sort-package-json: ^3.2.0

  nextjs:
    '@next/eslint-plugin-next': ^15.0.0
    next: ^15.0.0

  rollup:
    '@rollup/plugin-commonjs': ^28.0.0
    '@rollup/plugin-graphql': ^2.0.0
    '@rollup/plugin-image': ^3.0.0
    '@rollup/plugin-json': ^6.0.0
    '@rollup/plugin-node-resolve': ^16.0.0
    '@rollup/plugin-typescript': ^12.0.0
    '@rollup/plugin-yaml': ^4.0.0
    rollup: ^4.0.0
    rollup-plugin-postcss: ^4.0.0
    rollup-plugin-tsconfig-paths: ^1.0.0
    rollup-plugin-visualizer: ^6.0.0

  runtime:
    '@npmcli/run-script': ^10.0.0
    callsite-record: ^4.1.0
    chalk: ^5.3.0
    debug: ^4.3.5
    '@types/debug': ^4.0.0
    execa: ^9.3.0
    find-up-simple: ^1.0.0
    globby: ^15.0.0
    jiti: ^2.4.0
    js-yaml: ^4.1.0
    '@types/js-yaml': ^4.0.0
    listr2: ^9.0.0
    mvdan-sh: ^0.10.0
    pupa: ^3.1.0
    source-map-support: ^0.5.0
    yargs: ^18.0.0
    '@types/yargs': ^17.0.0
    yargs-parser: ^22.0.0

  storybook:
    '@storybook/addon-a11y': ^9.0.0
    '@storybook/addon-vitest': ^9.0.0
    '@storybook/nextjs-vite': ^9.0.0
    storybook: ^9.0.0
    storybook-addon-pseudo-states: ^9.0.0
    storybook-addon-test-codegen: ^2.0.0

  testing:
    '@vitest/coverage-v8': ^3.0.0
    vitest: ^3.0.0

  types:
    type-fest: ^5.0.0
    '@types/node': ^24.0.0

  utilities:
    cross-env: ^10.0.0
    dotenv-cli: ^10.0.0
    zx: ^8.0.0

  web:
    autoprefixer: ^10.0.0
    postcss: ^8.0.0
    postcss-preset-env: ^10.0.0
    '@tailwindcss/postcss': ^4.0.0
    tailwindcss: ^4.0.0
    prettier-plugin-tailwindcss: '*'
    globals: ^16.0.0

nodeLinker: hoisted # don't use symlinks

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

shamefullyHoist: true # hoist all dependencies to the root's node_modules
