/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Presetter Documentation",
  "tagline": "Configuration Management That Scales With Your Projects",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://alvis.github.io",
  "baseUrl": "/presetter/",
  "organizationName": "alvis",
  "projectName": "presetter",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/alvis/presetter/tree/master/website/",
          "breadcrumbs": true,
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "routeBasePath": "/docs",
          "include": [
            "**/*.md",
            "**/*.mdx"
          ],
          "exclude": [
            "**/_*.{js,jsx,ts,tsx,md,mdx}",
            "**/_*/**",
            "**/*.test.{js,jsx,ts,tsx}",
            "**/__tests__/**"
          ]
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/alvis/presetter/tree/master/website/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn",
          "blogTitle": "Presetter Blog",
          "blogDescription": "News, updates, and guides about Presetter configuration management",
          "postsPerPage": 5,
          "blogSidebarTitle": "All posts",
          "blogSidebarCount": "ALL"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/presetter-logo.svg",
    "metadata": [
      {
        "name": "description",
        "content": "Presetter documentation - Configuration management that scales with your projects"
      },
      {
        "name": "keywords",
        "content": "presetter, typescript, configuration, preset, eslint, prettier, build, tooling"
      },
      {
        "property": "og:description",
        "content": "Comprehensive documentation for Presetter, a TypeScript configuration management system"
      },
      {
        "property": "og:image",
        "content": "https://alvis.github.io/presetter/img/presetter-logo.svg"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:image",
        "content": "https://alvis.github.io/presetter/img/presetter-logo.svg"
      }
    ],
    "navbar": {
      "title": "Presetter",
      "logo": {
        "alt": "Presetter Logo",
        "src": "img/presetter-logo.svg"
      },
      "hideOnScroll": true,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "/docs/api",
          "label": "API Reference",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "href": "https://github.com/alvis/presetter",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/"
            },
            {
              "label": "Tutorials",
              "to": "/docs/tutorials/"
            },
            {
              "label": "API Reference",
              "to": "/docs/api/"
            },
            {
              "label": "CLI Reference",
              "to": "/docs/cli-reference/"
            }
          ]
        },
        {
          "title": "Presets",
          "items": [
            {
              "label": "Available Presets",
              "to": "/docs/presets/"
            },
            {
              "label": "React Preset",
              "to": "/docs/presets/frameworks/react"
            },
            {
              "label": "ESM Preset",
              "to": "/docs/presets/module-systems/esm"
            },
            {
              "label": "Monorepo Preset",
              "to": "/docs/presets/quality/monorepo"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub Issues",
              "href": "https://github.com/alvis/presetter/issues"
            },
            {
              "label": "GitHub Discussions",
              "href": "https://github.com/alvis/presetter/discussions"
            },
            {
              "label": "npm Package",
              "href": "https://www.npmjs.com/package/presetter"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/alvis/presetter"
            },
            {
              "label": "Changelog",
              "href": "https://github.com/alvis/presetter/releases"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Alvis HT Tang. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "typescript",
        "json",
        "yaml",
        "jsx",
        "tsx"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "error-next-line",
          "block": {
            "start": "error-start",
            "end": "error-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 5
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
