import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'doc',
        id: 'introduction/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction',
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      link: {
        type: 'doc',
        id: 'cli-reference/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli-reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Presets',
      link: {
        type: 'doc',
        id: 'presets/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'presets',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'tutorials/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      link: {
        type: 'doc',
        id: 'advanced/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced',
        },
      ],
    },
  ],
};

export default sidebars;