compilerOptions:
  # emittance
  outDir: '{output}'
  module: ESNext
  target: ESNext
  declaration: true
  inlineSourceMap: true

  # compatibility
  allowSyntheticDefaultImports: true
  esModuleInterop: true
  experimentalDecorators: true
  emitDecoratorMetadata: true
  isolatedModules: false
  jsx: react-jsx

  # module resolution
  moduleResolution: bundler
  resolveJsonModule: true
  baseUrl: .

  # libraries
  lib:
    - ES2020
    - ESNext
    - DOM
    - DOM.Iterable
include:
  - '**/*.json'
  - '**/*.ts'
  - '**/*.tsx'
exclude:
  - '**/node_modules'
