name: code coverage

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v4
      - name: use node lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: run coverage
        run: pnpm run coverage
        env:
          CI: true
      - name: upload coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage/lcov.info
