name: code coverage

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v4
      - name: use node lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: install code climate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
          chmod +x /tmp/cc-test-reporter
      - name: install dependencies
        run: pnpm install
      - name: run coverage
        run: pnpm run coverage
        env:
          CI: true
      - name: upload coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          /tmp/cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
          /tmp/cc-test-reporter upload-coverage
